### ISSUE TITLE
Loss of job tracking

### ISSUE THREAD

**Issue by jameshay218** [dide-tools/didewin#23]
After some time, the connection to the cluster drops and I cannot ping the status of jobs. eg.

`> real_inc_1$status();
Error in context_root(x$root) : context database not set up at contexts`

**Comment by richfitz** [comment]
This one is very odd; this does not depend on the cluster connection at all. Is this still the situation now?

**Comment by richfitz** [comment]
Closing as I don't think we ever replicated this
