### ISSUE TITLE
Potentially corrupt task ID database

### ISSUE THREAD

**Issue by jameshay218** [dide-tools/didewin#24]
Running cluster jobs that write output to the network drive. The disk runs out of space, which results in corrupted processes. These processes seem to become lost on the web portal and through the didewin tools, but retain a lock on the drive. 

```Error in:aa7caae7e6dd49e5ba5bcd047e019faf. Error is: Error in exists(name, envir = envir, inherits = FALSE): invalid first argument```

**Comment by richfitz** [comment]
This is going to be super hard for me to test with annoying Chris.  The new DB backend which will be available soon will also sidestep this issue
