### ISSUE TITLE
jobtemplate

### ISSUE THREAD

**Issue by tinigarske** [dide-tools/didewin#4]
My jobs are failing at the moment because they're so memory hungry, and the default seems to be to just request 1 core, and so they have to share the node's memory. That doesn't work for these.
Is there a way to request the whole node? And the 24Core template (that didn't work earlier yet, but I think you'd made a note of that already).

**Comment by richfitz** [comment]
I'll get that working ASAP tomorrow - checked with Wes and we're OK to use it.

However, the default *should* be to request 1 node any template apart from the GeneralNodes one.  At the same time it will also fire up a mini-cluster that you won't use - so I should set it up to not do that at the same time.

Can you post a log (can just be the start until things hand off to your code) so I can see what it looks like?

**Comment by tinigarske** [comment]
Thanks a lot! Usually I just use the GeneralNodes template, and then request the single node, or whatever number of cores I want. Is that what's not implemented yet?

The full log (\\fi--didenas3\Dengue\Code\aggregate_to_adm1\contexts\logs9fb1fc9e8d2ec7348bfac7c04719408e) is: 

args:
C:\Program Files\R\R-3.2.4revised\bin\x64\Rterm.exe, --slave, --no-restore, --file=W:\Code\aggregate_to_adm1\contexts\bin\context_runner, --args, W:\Code\aggregate_to_adm1\contexts, 9fb1fc9e8d2ec7348bfac7c04719408e
[ bootstrap ]  W:\Code\aggregate_to_adm1\contexts
[ lib       ]  W:\Code\aggregate_to_adm1\contexts/R/x86_64-w64-mingw32/3.2.4
[ ok        ]
[ init      ]  2016-04-27 14:10:20.946
[ version   ]  0.0.6
[ debug     ]  running as single core job
[ root      ]  W:\Code\aggregate_to_adm1\contexts
[ task      ]  9fb1fc9e8d2ec7348bfac7c04719408e
[ context   ]  fab85bf91f18496b066c57a8c21cad80
[ lib       ]  W:\Code\aggregate_to_adm1\contexts/R/x86_64-w64-mingw32/3.2.4
[ library   ]  maptools, raster, RColorBrewer, fields, rgdal
Loading required package: sp
rgdal: version: 1.1-8, (SVN revision 616)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.0.1, released 2015/09/15
 Path to GDAL shared files: W:/Code/aggregate_to_adm1/contexts/R/x86_64-w64-mingw32/3.2.4/rgdal/gdal
 GDAL does not use iconv for recoding strings.
 Loaded PROJ.4 runtime: Rel. 4.9.1, 04 March 2015, [PJ_VERSION: 491]
 Path to PROJ.4 shared files: W:/Code/aggregate_to_adm1/contexts/R/x86_64-w64-mingw32/3.2.4/rgdal/proj
 Linking to sp version: 1.2-3 
Loading required package: spam
Loading required package: grid
Spam version 1.3-0 (2015-10-24) is loaded.
Type 'help( Spam)' or 'demo( spam)' for a short introduction 
and overview of this package.
Help for individual functions is also obtained by adding the
suffix '.spam' to the function name, e.g. 'help( chol.spam)'.

Attaching package: 'spam'

The following objects are masked from 'package:base':

    backsolve, forwardsolve

Loading required package: maps

 # maps v3.1: updated 'world': all lakes moved to separate new #
 # 'lakes' database. Type '?world' or 'news(package="maps")'.  #


Checking rgeos availability: FALSE
 	Note: when rgeos is not available, polygon geometry 	computations in maptools depend on gpclib,
 	which has a restricted licence. It is disabled by default;
 	to enable gpclib, type gpclibPermit()
[ namespace ]
[ source    ]  aggregate_TS_to_adm.R, repair_shapefiles.R, source_last_dates.R
[ expr      ]  aggregate.TS.to.adm(adm0 = "COD", adm.lev = 1, year.i.input = 2007,[ expr      ]      year.f.input = 2014, file.type = "evi")
[ start     ]  2016-04-27 14:10:23.727
Error : cannot allocate vector of size 16.5 Gb
In addition: There were 11 warnings (use warnings() to see them)
[ error     ]
[ end       ]  2016-04-27 16:07:20.675

**Comment by richfitz** [comment]
Everything is implemented except for the 24Core job template is not available via the interface because I thought it was not OK to use (it is now).  The other issue is just that a little 24 core minicluster will get started on that node for you if all goes well, but that's a bit of a waste in your case.

That looks like the template argument might not have stuck correctly.  Can you dig out the batch file for that at some point (it will be at `batch/9fb1fc9e8d2ec7348bfac7c04719408e.bat`)

**Comment by tinigarske** [comment]
For this submission, I didn't actually use any template command, just the simpler version:

obj = didewin::queue_didewin(ctx)
job.list = ...
my.task = queuer::enqueue_bulk(obj, job.list, aggregate.TS.to.adm, do.call = TRUE, timeout = 0)

Is there  a way to specify the equivalent of the /numnodes:1 /singlenode:false or the /numcores:4-4 type commands?

batch file below:

REM automatically generated
REM   date: 2016-04-27 14:10:19
REM   didewin version: 0.0.1
REM   context version: 0.0.6
set CONTEXT_TASK_ID=9fb1fc9e8d2ec7348bfac7c04719408e
set CONTEXT_WORKDRIVE=W:
set CONTEXT_WORKDIR=Code\aggregate_to_adm1
set CONTEXT_ROOT=W:\Code\aggregate_to_adm1\contexts
set CONTEXT_LOGFILE=W:\Code\aggregate_to_adm1\contexts\logs\9fb1fc9e8d2ec7348bfac7c04719408e
call setr64_3_2_4.bat
net use W: \\fi--didenas3\Dengue /y
net use Q: \\fi--san02\homes\tinigarske /y
net use T: \\fi--didef2\tmp /y
%CONTEXT_WORKDRIVE%
cd \%CONTEXT_WORKDIR%
cd
echo Logging to %CONTEXT_LOGFILE%
Rscript %CONTEXT_ROOT%\bin\context_runner %CONTEXT_ROOT% %CONTEXT_TASK_ID% > %CONTEXT_LOGFILE% 2>&1

**Comment by richfitz** [comment]
Yup, but those go through the queue setup for now. If you select a template other than GeneralNodes you'll get 1 node.  Or you can pass cores=16 or whatever to get a bunch of cores.  The submission uses the configuration that the queue has.

This stuff all has an effect *before* the batch file, now that I think about it.

**Comment by richfitz** [comment]
Closed in d58abb0
